# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09167ac57026db73da83a25852761b5b229a41c553e67d9075e9af5e9f8bde8b775a019bc0a957d10c91179125f1897995164b7f9b63236f014529005c08b5e

test:
  secret_key_base: 356aa8e4866efbb28cb0c5177b6b738234353816f20fd1441bf9e122293c238fe1de5ce284da7cb0686731df30282fbf8527f28dfeedabe9d7e9ffa13ddf7a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
